apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-service
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  strategy: {}
  template:
    metadata:

      labels:
        app: inventory-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-inventory:5432/inventory-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: eureka.client.serviceUrl.defaultZone
              value: http://root:root@discovery-server-service:8761/eureka     
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: root              
          image: hmishra609/inventory-service:latest
          name: inventory-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service-nodeport
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 8080
      targetPort: 8080
      nodePort : 30070
  selector:
    app: inventory-service
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-service
  name: inventory-service
spec:
  ports:
    - name: "80"
      port: 8080
      targetPort: 8080
  selector:
    app: inventory-service
status:
  loadBalancer: {}
