apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:

      labels:
        app: order-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-order:5431/order-service
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: eureka.client.serviceUrl.defaultZone
              value: http://root:root@discovery-server-service:8761/eureka     
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: root                                     
          image: hmishra609/order-service:latest
          name: order-service
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 8080
      targetPort: 8080
      nodePort : 30093
  selector:
    app: order-service
status:
  loadBalancer: {}
