apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres-order
  name: postgres-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - args:
            - -p
            - "5431"
          env:
            - name: PGDATA
              value: /data/postgres
            - name: POSTGRES_DB
              value: order-service
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_USER
              value: root
          image: postgres
          name: postgres-order
          ports:
            - containerPort: 5431
          resources: {}
          volumeMounts:
            - mountPath: /data/postgres
              name: postgres-order-claim0
      restartPolicy: Always
      volumes:
        - name: postgres-order-claim0
          persistentVolumeClaim:
            claimName: postgres-order-claim0
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-order
  name: postgres-order
spec:
  ports:
    - name: "5431"
      port: 5431
      targetPort: 5431
  selector:
    app: postgres-order
status:
  loadBalancer: {}
---

apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgres-data-order # Sets PV's name
  labels:
    type: postgres-order # Sets PV's type to local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi # Sets PV Volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/cloud_user/data/postgresOrder" # Sets the volume's path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  creationTimestamp: null
  labels:
    type: postgres-order
  name: postgres-order-claim0
spec:
  storageClassName: manual
  selector:
    matchLabels:
      type: postgres-order #this will boind the pv with same label  
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 100Mi # Sets volume size



